<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>fileTypes</key>
    <array/>
    <key>name</key>
    <string>Log Highlight</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>begin</key>
            <string>Log Highlight</string>
            <key>comment</key>
            <string>...</string>
            <key>end</key>
            <string>[\r\n]</string>
            <key>name</key>
            <string>summary.title</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^Error-\[</string>
            <key>end</key>
            <string>^\s*[\n]</string>
            <key>name</key>
            <string>msg.error</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#error_link</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#error_quote</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(["']?[\w\d\:\\/\.\-\=]+\.\w+[\w\d]*["']?\s*[,:on line\(]{1,9}\s*\d+\)?)?[^\r\n]*?(?i)error</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>msg.error.link</string>
                </dict>
            </dict>
            <key>end</key>
            <string>[\r\n]</string>
            <key>name</key>
            <string>msg.error</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#error_link</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#error_quote</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>^\w+:\s*\*E</string>
            <key>end</key>
            <string>[\r\n]</string>
            <key>name</key>
            <string>msg.error</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#error_link</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#error_quote</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>^Warning-\[</string>
            <key>end</key>
            <string>^\s*[\n]</string>
            <key>name</key>
            <string>msg.warning</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#warning_link</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#warning_quote</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(["']?[\w\d\:\\/\.\-\=]+\.\w+[\w\d]*["']?\s*[,:on line\(]{1,9}\s*\d+\)?)?[^\r\n]*?(?i)warning</string>
            <key>beginCaptures</key>
            <dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>msg.warning.link</string>
                </dict>
            </dict>
            <key>end</key>
            <string>[\r\n]</string>
            <key>name</key>
            <string>msg.warning</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#warning_link</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#warning_quote</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>begin</key>
            <string>^\w+:\s*\*W</string>
            <key>end</key>
            <string>[\r\n]</string>
            <key>name</key>
            <string>msg.warning</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#warning_link</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#warning_quote</string>
                </dict>
            </array>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>error_link</key>
        <dict>
            <key>match</key>
            <string>["']?[\w\d\:\\\/\.\-\=]+\.\w+[\w\d]*["']?\s*[,:on line\(]{1,9}\s*\d+\)?</string>
            <key>name</key>
            <string>msg.error.link</string>
        </dict>
        <key>error_quote</key>
        <dict>
            <key>match</key>
            <string>(["'])(?:(?=(\\?))\2.)*?\1</string>
            <key>name</key>
            <string>msg.error.quote</string>
        </dict>
        <key>warning_link</key>
        <dict>
            <key>match</key>
            <string>["']?[\w\d\:\\\/\.\-\=]+\.\w+[\w\d]*["']?\s*[,:on line\(]{1,9}\s*\d+\)?</string>
            <key>name</key>
            <string>msg.warning.link</string>
        </dict>
        <key>warning_quote</key>
        <dict>
            <key>match</key>
            <string>(["'])(?:(?=(\\?))\2.)*?\1</string>
            <key>name</key>
            <string>msg.warning.quote</string>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>source.loghighlight</string>
    <key>uuid</key>
    <string>0ed2482c-a94a-49dc-9aae-b1401bcff2e0</string>
</dict>
</plist>
