<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Log Highlight</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>Log Highlight</string>
			<key>comment</key>
			<string>...</string>
			<key>end</key>
			<string>[\r\n]</string>
			<key>name</key>
			<string>summary.title</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>.+?(?i)error</string>
			<key>comment</key>
			<string>...</string>
			<key>end</key>
			<string>[\r\n]</string>
			<key>name</key>
			<string>msg.error</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\"?[\w\d\:\\/\.\-\=]+\.\w+[\w\d]*\"?[,:]\s*\d+</string>
					<key>name</key>
					<string>msg.error.link</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\')[^\']+(?=\')</string>
					<key>name</key>
					<string>msg.error.quote</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>.+?(?i)warning</string>
			<key>comment</key>
			<string>...</string>
			<key>end</key>
			<string>[\r\n]</string>
			<key>name</key>
			<string>msg.warning</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\"?[\w\d\:\\/\.\-\=]+\.\w+[\w\d]*\"?[,:]\s*\d+</string>
					<key>name</key>
					<string>msg.warning.link</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\')[^\']+(?=\')</string>
					<key>name</key>
					<string>msg.warning.quote</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.log_highlight</string>
	<key>uuid</key>
	<string>0da65be4-5aac-4b6f-8071-1aadb970b8d9</string>
</dict>
</plist>
